name: Build Python Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.6'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install buildozer
          pip install cython==0.29.33

      - name: Initialize Buildozer (if needed)
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Build Android APK
        run: |
          buildozer -v android debug
          ls -la bin/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: bin/*.apk
